AskdjangoBasic/askcompany/askcompany/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('blog/',include('blog.urls')),
   
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns+=[  path('__debug__/', include(debug_toolbar.urls)),]

AskdjangoBasic/askcompany/blog/urls.py
from django.urls import path

app_name='blog'

urlpatterns=[

]

AskdjangoBasic/askcompany/shop/urls.py
from django.urls import path, re_path , register_converter
from .converters import FourDigitYearConverter  
from .import views
from .views import item_list

register_converter(FourDigitYearConverter,'yyyy')

app_name='shop'

urlpatterns=[
    path('archives/<yyyy:year>/', views.archives_year,name='archives_year'),
    path('',views.item_list,name='item_list'),
    path('<int:pk>/',views.item_detail,name='item_detail'),
    #path(r'^(?P<pk>\d+)/$',views.item_detail), 위와 같은 선언
    path('new/',views.item_new,name='item_new'),
    path('<int:pk>/edit/',views.item_edit,name='item_edit'),

]

AskdjangoBasic/askcompany/blog/models.py
from django.db import models
from askcompany.utils import uuid_upload_to
from django.conf import settings
# Create your models here.
#11강 
#python manage.py migrate <앱이름><마이그레이션-이름>
#<마이그레이션-이름>이 마지막 migrate가 되어야함 ex 1 2 3 migrate진행 python manage.py migrate blog 002 이면 3번 migrate는 취소

#이미 migrate를 한 상태에서 추가로 post에 필드를 집어넣는 다면 기존 record들에 어떤 값으로 채워넣을 지 묻는 것- 직접입력/blank
class Post(models.Model):
    author_name=models.CharField(max_length=20,blank=True)  #이때 blank가 기존 record를 blank로 채워넣겠다는 의미
    title=models.CharField(max_length=100,db_index=True)
    content=models.TextField(blank=True)
    photo=models.ImageField(uuid_upload_to)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE) #on_delete...속해있는 post가 삭제되면 comment도 삭제하겠다라는 의미 
    message=models.TextField()



#15강 올바른 user 모델 지정
#blog/models.py
#class Post(models.Model):
#    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

#django/contrib/auth/models.py
#class User (AbstractBaseUser)

#특정 포스트에 속한 코멘트 불러오기-> post.comment_set.all() == Comment.objects.filter(post=post)

AskdjangoBasic/askcompany/shop/models.py
from django.db import models
from askcompany.utils import uuid_upload_to
from django.conf import settings
from django.urls import reverse
"auth.User" #앱에 대한 외래키
#모델 클래스명은 단수형으로 지정
#첫 글자를 대문자로 네이밍
#charfield:길이제한 textfield:길이제한 없음 slugfield:charfield를 상속받은 것. slug(뉴스 기사에 url에 해당 뉴스에 대한 제목이 붙음)목적으로 사용
#파일: FileField: ImageField: 업로드된 파일은 데이터베이스에 저장되지 않음.파일이 저장된 경로를 저장. binaryfield는 성능이 좋지않음. filepathfield: 경로만 저장. 
#email,url -> db입장에서는 charfield
#foreignkey ->일반적인 하나의 포스트에 여러개의 commentmanytomanyfield->다대다 관계 1개의 포스트에 다수의 태그, 1개의 태그에는 다수의 포스트
class Item(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField(blank=True)   #빈경우도 허용하겠다.
    price=models.PositiveIntegerField()
    photo=models.ImageField(blank=True ,upload_to=uuid_upload_to)
    is_publish=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    def __str__(self):  #item에서 이름 보이도록
        #return self.name
        return f'<{self.pk} {self.name}>'
    def get_absolute_url(self):
        #return reverse('shop:item_detail',args=[self.pk])
        return reverse('shop:item_detail',kwargs={'pk':self.pk})

class Post(models.Model):  #충돌 실험
    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#13강 queryset조회 방법
#queryset[index] 는 객체 1개만 획득
#queryset.get(..) 1개만 가져옴. 없거나 2개이상이면 오류발생
#queryset.first() 첫번째 .last()마지막 만약 없다면 none을 return함 오류를 발생시키지않음
#queryset.filter('') ,exclude('') & | 가능
#lt less than lte less than equal
#g greter

AskdjangoBasic/askcompany/shop/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields='__all__'
        

AskdjangoBasic/askcompany/shop/views.py
from django.http import HttpResponse, Http404, HttpResponseNotFound
from django.http import HttpResponseRedirect
from django.http.response import Http404
from django.shortcuts import render, redirect , resolve_url, get_object_or_404
from shop.models import Item
from django.http import HttpResponse, JsonResponse
# Create your views here.
from .models import Item
import re
from .forms import ItemForm


#07강 http 상태코드로 응답
#200번대: 성공 300번대: 요청을 마치기 위해ㅣ 추가동작 400번대: 클라이언트측 오류 500번대 서버측 오류(indexerror,keyerror,django,db,models.objectdoesnotexist등)

#200번대 
def view1(request):
    return HttpResponse('Hello, Ask Company')
def view2(request):
    return render(request, 'template.html')
def view3(request):
    return JsonResponse({'hello': 'Ask Company'}) #객체를 문자열로 변환한다음 return 해야하는데 이때 response를 사용하면 내부적으로 변환해줌

#302 응답하는 예시
def view1(request):
    return HttpResponseRedirect('/shop/')

def view2(request):
    url=resolve_url('shop:item_list')
    return HttpResponseRedirect(url)
def view3(request):                         #view2 코드를 한줄로
    return redirect('shop:item_list')

#404 응답하는 예시  try except를 통해 item이 없을 때 오류를 잡을 수 있다. or get_object_or_404의 조건을 통해
def view1(request):  
    try:
        item=Item.objects.get(pk=100)
    except Item.DoesNotExist:
        raise Http404
def view2(request):
    item=get_object_or_404(Item,pk=100)
def view3(request):
    try:
        item-Item.objects.get(pk=100)
    except Item.DoesNotExist:
        return HttpResponseNotFound()

#500 응답하는 에시
def view1(request):
    name=['Tom','Steve'][100] #idex error

    item=Item.objects.get(pk=100) # item레코드가 없거나 1개 있을 때 dosenotExist 예외  그이상이면 multipleObjectsReturn

def archives_year(request,year):
    return HttpResponse('{}년도에 대한 내용'.format(year))

def item_list(request):
    qs=Item.objects.all()  #model에서 Item 선언해줘야함
    
    q=request.GET.get('q','')
    if q:
        qs=qs.filter(name__icontains=q)  #대소문자 구별하지 않겠따.
    return render(request,'shop/item_list.html', {
        'item_list': qs, 

        })

def item_detail(request,pk):
    item=get_object_or_404(Item, pk=pk)
    return render(request,'shop/item_detail.html',{
        'item': item,
    })

def item_new(request, item=None):

    if request.method == 'POST':
        form=ItemForm(request.POST,request.FILES, instance=item)
        if form.is_valid():
            item=form.save()
            return redirect(item)

    else:
        form=ItemForm(instance=item)

    return render(request, 'shop/item_form.html', {
        'form':form,
    })


def item_edit(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return item_new(request, item)

#item_new=CreateView.as_view(model=Item,form_class=ItemForm) 함수 기반 뷰 from django.views.generic import CreateView,UpdateView
# #item_edit=UpdateView.as_view(model=Item,form_classItemForm)

AskdjangoBasic/askcompany/askcompany/templates/layout.html
{% load static fresh_static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Ask Company{%endblock%}</title>
    <style>
        body{background-color:lightyellow;}
    </style>
    {% block extra_head %}
    <link rel="stylesheet" href="{%fresh_static "main.css" %}"/>
    {%endblock%}
</head>

<body>
    <h1>Ask Company</h1>
    {% block content %}
    {% endblock %}

    <hr/>
    &copy: 2021. Ask
    
    {% block extra_body %}
    <script src="{% static "main.js" %}"></script>
    {%endblock%}
</body>

</html>

AskdjangoBasic/askcompany/blog/templates/blog/layout.html
{% extends "layout.html" %}
{%load fresh_static%}
{% block title %}Blog by Ask Company{% endblock %}

{%block extra_head%}

{{block.super}}
<link rel="stylesheet" href="{% fresh_static "blog/blog.css" %}"/>

{%endblock%}

{%block extra_body%}
{{block.super}}
{%endblock%}

AskdjangoBasic/askcompany/shop/templates/shop/item_detail.html
{% extends "shop/layout.html" %}
{% load humanize %}

{% block content %}

    <h2>{{ item.name }}</h2>

    {% if item.photo %}
        <img src="{{item.photo.url}}" style="max-width: 100;" />   <!--실제 .url을 통한 접근에서-->
        {{item.photo.path}}<br/>
        <!--media root와 조합/ -->
    {%endif%}
    가격:{{item.price|intcomma}}원
    <!--가격에 ,를 생성 humanize-->

    {% if item.desc %}
        <p>
            {{ item.desc }}
        </p>
    {%endif%}

    <hr />
    <a href="{%url "shop:item_list" %}">목록</a>
    <a href="{%url "shop:item_edit" item.pk %}">수정</a>
{% endblock %}

AskdjangoBasic/askcompany/shop/templates/shop/item_form.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <div class="col-sm-12">
                <h2>New Item</h2>
               
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    <table class="table table-bordered">
                        {{form.as_table}}
                    </table>
                    <input type="submit" value="저장하기" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </body>
</html> 

AskdjangoBasic/askcompany/shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}

{% block content %}
<form action="" method="GET">
    <input type="text" name="q" value="{{q}}" />
    <input type="submit" value="검색" />
</form>

<hr />

{% for item in item_list %}
<div>
    <a href="{{item.get_absolute_url}}">
        <h3>{{item.name}}</h3>
    </a>
    <h4>가격: {{item.price}}</h4>

    <p>{{item.desc}}</p>
    {% endfor %}
</div>
<hr/>
<a href="{%url "shop:item_new"%}">New Item</a>
{% endblock %}

AskdjangoBasic/askcompany/shop/templates/shop/layout.html
{%  extends "layout.html" %}
{%load static%}
{% block title %}Shop by Ask Company{% endblock %}
{%block extra_head%}
{{block.super}}
{{block.super}}
<link rel="stylesheet" href="{% static "shop/shop.css" %}/>
{%endblock%}

{%block extra_body%}
{{block.super}}
{%endblock%}