SWIDEA_SITE/config/devtool/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name='devtool'


urlpatterns=[
    path('',views.devtool_list,name='devtool_list'),
    path('create/',views.devtool_create,name="devtool_create"),
    path('<int:pk>/',views.devtool_detail,name="devtool_detail"),
    path('update/<int:pk>/',views.devtool_update,name="devtool_update"),
    path('delete/<int:pk>/',views.devtool_delete,name="devtool_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/config/devtool/models.py
from django.db import models

class Devtool(models.Model):
    name=models.CharField(max_length=50)
    type=models.CharField(max_length=50)
    explain=models.TextField(blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

SWIDEA_SITE/config/devtool/forms.py
from django import forms
from .models import Devtool


class DevtoolForm(forms.ModelForm):
    class Meta:
        model=Devtool
        fields='__all__'
        

SWIDEA_SITE/config/devtool/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect , resolve_url, get_object_or_404
import json
from .forms import DevtoolForm
from .models import Devtool
from idea.models import Idea
app_name='devtool'
def devtool_list(request):
    all_devtool=Devtool.objects.all()
    return render(request,'devtool/devtool_list.html',{
        'all_devtool':all_devtool,
    })

def devtool_create(request,devtool=None):
    if request.method=='POST':

        form=DevtoolForm(request.POST,request.FILES, instance=devtool)
        if form.is_valid():
            devtool=form.save()
            return redirect('/devtool/'+str(devtool.pk))
    else:
        form=DevtoolForm(instance=devtool)

    return render(request, 'devtool/devtool_create.html', {
        'form':form,
        })


def devtool_detail(request,pk):
    devtool=get_object_or_404(Devtool, pk=pk)
    ideas=devtool.idea_set.all()
    return render(request,'devtool/devtool_detail.html',{
        'devtool':devtool,
        'ideas':ideas,
    })

def devtool_update(request,pk):
    devtool = get_object_or_404(Devtool, pk=pk)
    return devtool_create(request, devtool)

def devtool_delete(request,pk):
    devtool = get_object_or_404(Devtool, pk=pk)
    devtool.delete()
    return redirect('devtool:devtool_list')

SWIDEA_SITE/config/devtool/templates/devtool/devtool_create.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <div class="col-sm-12">
                <h2>New Idea</h2>
               
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    <table class="table table-bordered">
                        {{form.as_table}}
                    </table>
                    <input type="submit" value="저장하기" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </body>
</html> 

SWIDEA_SITE/config/devtool/templates/devtool/devtool_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>

<body>
    <div>
        <h1>DevTool Detail</h1>
        <h3>개발툴 세부내용 페이지입니다. 자신이 다룰 수 있는 개발툴에 대한 상세 내용을 확인해보세요.</h3>
    </div>
    <hr/>

    <h2>{{devtool.name}}<br /></h2>
    
    <h5>{{devtool.type}}<br /></h5>
    <h5>{{devtool.explain}}<br /></h5>
    <h3>>만들 수 있는 sw목록</h3>
  
    {%for idea in ideas%}
    <a href="{% url "idea:idea_detail" idea.pk %}">{{idea.title}}</a>
    {%endfor%}
    <br/>
    <br/>
    <a href="{%url "devtool:devtool_delete" devtool.pk %}">삭제</a>
    <a href="{%url "devtool:devtool_list" %}">목록</a>
    <a href="{%url "devtool:devtool_update" devtool.pk %}">수정</a>
    <hr/>
    


    
</body>

</html>

SWIDEA_SITE/config/devtool/templates/devtool/devtool_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>

<body>
    <div>
        <h1>DevTool List</h1>
        <h3>개발툴 목록 페이지입니다. 자신이 사용가능한 개발툴의 목록을 확인해보세요.</h3>
    </div>
    <hr/>
    {% for devtool in all_devtool %}
    
    <a href="{% url "devtool:devtool_detail" devtool.pk %}">
        <h2>{{devtool.name}}<br /></h2>
    </a>
   
    
    <h4>{{devtool.type}}<br /></h4>
    <h5>{{devtool.explain}}<br /></h5>
    <hr/>
    

    {%endfor%}
    
</body>

</html>