SWIDEA_SITE/config/idea/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name='idea'


urlpatterns=[
    path('',views.idea_list,name='idea_list'),
    path('idea/<int:pk>/',views.idea_detail,name='idea_detail'),
    path('idea/create/',views.idea_create,name="idea_create"),
    path('idea/upate/<int:pk>',views.idea_update,name='idea_update'),
    path('idea/delete/<int:pk>',views.idea_delete,name='idea_delete'),
#    path('interest/',views.idea_interest,name="idea_interest"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/config/idea/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
class Idea(models.Model):
    title=models.CharField(max_length=50)
    image=models.ImageField(blank=True ,upload_to="idea_image/%Y/%m/%d/")
    content=models.TextField(blank=True)
    interest=models.IntegerField(default=0)
    devtool=models.ForeignKey(verbose_name="예상 계발툴",to='devtool.Devtool',on_delete=models.SET_NULL, null=True, blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

SWIDEA_SITE/config/idea/forms.py
from django import forms
from .models import Idea


class IdeaForm(forms.ModelForm):
    class Meta:
        model=Idea
        fields='__all__'
        

SWIDEA_SITE/config/idea/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect , resolve_url, get_object_or_404
from .models import Idea
import json
from .forms import IdeaForm
from django.http import HttpResponse

from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def idea_list(request):
    all_idea=Idea.objects.all()
    ctx={
        'all_idea':all_idea,
        
    }
    return render(request,'idea/idea_list.html',ctx)

'''
def idea_interest(request):
        p=request.POST.get('pk',None)
        i=request.POST.get('interest',None)
        idea = get_object_or_404(Idea, pk=p)
        idea.interest=i
        idea.save()
        ctx={
        'pk':p,
        'interest':idea.interest,
        
        }
        return render(request,'idea/idea_list.html',ctx)

'''


def idea_detail(request,pk):
    idea=get_object_or_404(Idea, pk=pk)
    devtool=idea.devtool
    return render(request,'idea/idea_detail.html',{
        'idea':idea,
        'devtool':devtool,
    })

def idea_create(request,idea=None): 
    if request.method=='POST':

        form=IdeaForm(request.POST,request.FILES, instance=idea)
        if form.is_valid():
            idea=form.save()
            return redirect('/idea/'+str(idea.pk))
    else:
        form=IdeaForm(instance=idea)

    return render(request, 'idea/idea_form.html', {
        'form':form,
        })
 

def idea_update(request,pk):
    idea = get_object_or_404(Idea, pk=pk)
    return idea_create(request,idea)

def idea_delete(request,pk):
    idea = get_object_or_404(Idea, pk=pk)
    idea.delete()
    return redirect('idea:idea_list')

SWIDEA_SITE/config/idea/templates/idea/idea_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>Idea Detail</h1>
        <h3>아이디어 세부내용 페이지 입니다. 당신이 구현하려 한 아이디어들을 자세히 살펴보세요.</h3>
    </div>
    {% if idea.image %}
    <img src="{{idea.image.url}}"   width="800"/><br />
    {%endif%}
    {{idea.title}}<br />
    <div>1.아이디어 관심도:</div>
    {{idea.interest}}<br />
    {%if idea.devtool%}
    <div>2.예상 계발 툴:</div>
    <a href="{%url "devtool:devtool_detail" devtool.pk %}">{{idea.devtool}}<br/></a>
    {%endif%}
    <div>3.아이디어 설명:</div>
    {{idea.content}}<br />
    <a href="{%url "idea:idea_delete" idea.pk %}">삭제</a>
    <a href="{%url "idea:idea_list" %}">목록</a>
    <a href="{%url "idea:idea_update" idea.pk %}">수정</a>
</body>
</html>

SWIDEA_SITE/config/idea/templates/idea/idea_form.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <div class="col-sm-12">
                <h2>New Idea</h2>
               
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    <table class="table table-bordered">
                        {{form.as_table}}
                    </table>
                    <input type="submit" value="저장하기" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </body>
</html> 

SWIDEA_SITE/config/idea/templates/idea/idea_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $.ajaxSetup({
          headers: { "X-CSRFToken": '{{csrf_token}}' }
        });
    </script>
    
</head>

<body>
    <div>
        <h1>Idea List</h1>
        <h3>나의 아이디어를 잊지말고 기록해보세요</h3>
    </div>
    {% for idea in all_idea %}
    {% if idea.image %}
    <img src="{{idea.image.url}}" width="400" /><br />
    {%endif%}
   
    <a href="{% url "idea:idea_detail" idea.pk %}">
        <h3>{{idea.title}}</h3>
    </a>
    예상 개발 툴: {{idea.devtool}}<br />
    
    <h2 id="number{{idea.pk}}">{{idea.interest}}</h2>
    <div>
        <button class="increase{{idea.pk}}">+</button>
        <button class="decrease{{idea.pk}}">-</button>
    </div>


    <script>

        
     
         
      
        
        $(".increase{{idea.pk}}").click(function() {
            
            var pk=parseInt(($(this).attr('class')).split("e")[2],10);   //increase뒤의 숫자를 split
            var id_number="#number"+pk;
        
            var number= document.querySelector(id_number);
            
            var current = parseInt(number.textContent, 10);
            
            
            
            console.log(pk)
            $.ajax({
                type: "POST", 
                url: "{% url 'idea:idea_list' %}",  //interest로 연결해봤지만 404오류 뜸..
                data: {'pk':pk ,'interest':number.textContent,csrfmiddlewaretoken: '{{ csrf_token }}'},
                contentType: "application/json",
                success: function(response){
                    number.textContent = current + 1;

                },
            });
        });
    

        $(".decrease{{idea.pk}}").click(function() {
            
            var pk=parseInt(($(this).attr('class')).slice(8,),10);   //decrease뒤의 숫자를 split
            var id_number="#number"+pk;
        
            var number= document.querySelector(id_number);
            
            var current = parseInt(number.textContent, 10);
            
            
            
            console.log(pk)
            $.ajax({
                type: "POST", 
                url: "{% url 'idea:idea_list' %}",
                data: {'pk':pk ,'interest':number.textContent,csrfmiddlewaretoken: '{{ csrf_token }}'},
                contentType: "application/json",
                success: function(response){
                    number.textContent = current - 1;
                 

                },
            });
        });

    </script>
    {%endfor%}
    
</body>

</html>